### ISSUE TITLE
Could not pass event BufferedLocationEvent to Wild

### ISSUE THREAD

**Issue by Nextopi** [hornta/wild#7]
I've got this error, what could have caused it ?

https://paste.gg/p/anonymous/3416b932e3184cd6bd33eb45349212ad/files/96b81bd05f0b476eb8c92a4f9276996b/raw

**Comment by hornta** [comment]
Can you enable verbose mode in the config.ymland see if theres more output?

**Comment by Nextopi** [comment]
no verbose message after that, but it seems to happen when I'm in a world that is not handled by multiverse, a world made by dungeonsxl

**Comment by hornta** [comment]
@Nextopi Is that an overworld world?

**Comment by hornta** [comment]
Can you chat me up on Discord so we can talk more about this: hornta#4659

**Comment by Nextopi** [comment]
ok
